export const Salescolumns = [
  { accessorKey: 'division', header: 'DIV' },
  { accessorKey: 'name', header: 'DIV NAME' },
  { accessorKey: 'sale', header: 'GROSS SALE(A)' },
  { accessorKey: 'saleable', header: 'SALEABLE RET. (B)' },
  { accessorKey: 'nonsaleable', header: 'NON-SALEABLE RET. (C)' },
  { accessorKey: 'diff', header: 'PRICE DIFF RET.(D)' },
  { accessorKey: 'netsales', header: 'NET SALES (E=A-B-C-D)' },
  { accessorKey: 'pend_pick', header: 'PENDING FOR INVOICE (F)' },
  { accessorKey: 'pend_ord', header: 'PENDING FOR PACKING (G)' },
  { accessorKey: 'pend_disp', header: 'PENDING FOR DISPATCHES H(F+G)' },
  { accessorKey: 'unconf_ostd_ord', header: 'UNCONF DUE TO OS (I)' },
  { accessorKey: 'unconf_stock', header: 'UNCONF DUE TO STOCK (J)' },
  { accessorKey: 'unconf_total', header: 'TOTAL UNCONF (K=I+J)' },
  { accessorKey: 'for_ord', header: 'SCORE CARD' },
  { accessorKey: 'net_amt', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACHIEVEMENT (%)' },
  { accessorKey: 'varv', header: 'VAR' },
  { accessorKey: 'percRet', header: '% RET' },
  { accessorKey: 'lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'lymtd1', header: 'LAST YEAR' },
  { accessorKey: 'growth_cy', header: 'LAST YEAR GROWTH' },
];

export const divHqPopupColumns = [
  { accessorKey: 'vkbur', header: 'HQ' },
  { accessorKey: 'bezei', header: 'HQ NAME' },
  { accessorKey: 'msr', header: 'MSR' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES (E=A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING FOR INVOICE (F)' },
  { accessorKey: 'pend_ord1', header: 'PENDING FOR PACKING (G)' },
  { accessorKey: 'pend_disp', header: 'PENDING FOR DISPATCHES H(F+G)' },
  { accessorKey: 'unconf_ostd_ord1', header: 'UNCONF DUE TO OS (I)' },
  { accessorKey: 'unconf_stock', header: 'UNCONF DUE TO STOCK (J)' },
  { accessorKey: 'unconf_total', header: 'TOTAL UNCONF (K=I+J)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'percRet', header: '% RET' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
  { accessorKey: 'ytoamt', header: 'OS' },
  { accessorKey: 'tcamt1', header: 'Collection' },
  { accessorKey: 'ttgt_coll', header: 'Collection Target' },
  { accessorKey: 'mcamt1', header: 'Collection LMTD' },
  { accessorKey: 'ycamt1', header: 'Collection LYTD' },
];

export const divBrandPopupColumns = [
  { accessorKey: 'brand_code', header: 'BRAND CODE' },
  { accessorKey: 'brand_name', header: 'BRAND NAME' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES (H=A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING FOR PACKING (L)' },
  { accessorKey: 'total1', header: 'O(H+L)' },
  { accessorKey: 'pend_ord1', header: 'PENDING ORDER (M)' },
  { accessorKey: 'total_ord1', header: 'N(O+M)' },
  { accessorKey: 'unconf_ord1', header: 'UNCONF ORDER VALUE (U)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
];

export const divHierarchyPopupColumns = [
  { accessorKey: 'div', header: 'Division' },
  { accessorKey: 'name', header: 'Dsm/Rm Name' },
  { accessorKey: 'scorecard', header: 'ScoreCard' },
  { accessorKey: 'net_amount', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'var', header: 'VAR' },
  { accessorKey: 'percRet', header: '% RET' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
];

export const divPlantPopupColumns = [
  { accessorKey: 'werks', header: 'Plant' },
  { accessorKey: 'plant', header: 'Plant Name' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES(E = A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING FOR INVOICE (F)' },
  { accessorKey: 'pend_ord1', header: 'PENDING FOR PACKING (G)' },
  { accessorKey: 'pend_disp', header: 'PENDING FOR DISPATCHES H(F+G)' },
  { accessorKey: 'unconf_ostd_ord1', header: 'UNCONF DUE TO OS (I)' },
  { accessorKey: 'unconf_stock', header: 'UNCONF DUE TO STOCK (J)' },
  { accessorKey: 'unconf_total', header: 'TOTAL UNCONF (K=I+J)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR' },
  { accessorKey: 'ytoamt', header: 'OS' },
  { accessorKey: 'tcamt1', header: 'Collection' },
  { accessorKey: 'ttgt_coll', header: 'Collection Target' },
  { accessorKey: 'mcamt1', header: 'Collection LMTD' },
  { accessorKey: 'ycamt1', header: 'Collection LYTD' },
];

export const divCustPopupColumns = [
  { accessorKey: 'kunnr', header: 'Customer' },
  { accessorKey: 'name1', header: 'Customer Name' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES(E = A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING FOR INVOICE (F)' },
  { accessorKey: 'pend_ord1', header: 'PENDING FOR PACKING (G)' },
  { accessorKey: 'pend_disp', header: 'PENDING FOR DISPATCHES H(F+G)' },
  { accessorKey: 'unconf_ostd_ord1', header: 'UNCONF DUE TO OS (I)' },
  { accessorKey: 'unconf_stock', header: 'UNCONF DUE TO STOCK (J)' },
  { accessorKey: 'unconf_total', header: 'TOTAL UNCONF (K=I+J)' },
  { accessorKey: 'status', header: 'Status' },  
  { accessorKey: 'net_amt1', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'percRet', header: '% RET' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
  { accessorKey: 'ytoamt', header: 'OS' },
  { accessorKey: 'tcamt1', header: 'Collection' },
  { accessorKey: 'ttgt_coll', header: 'Collection Target' },
  { accessorKey: 'mcamt1', header: 'Collection LMTD' },
  { accessorKey: 'ycamt1', header: 'Collection LYTD' },
];

export const RegionReportColumns = [
  { accessorKey: 'regio', header: 'Region' },
  { accessorKey: 'region_desc', header: 'Region Name' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES(H = A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING PICKLIST(L)' },
  { accessorKey: 'total1', header: 'O(H+L)' },
  { accessorKey: 'pend_ord1', header: 'PENDING ORDER(M)' },
  { accessorKey: 'total_ord1', header: 'N(O+M)' },
  { accessorKey: 'unconf_ord1', header: 'UNCONF ORDER VALUE(U)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT(N+U)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
]

export const RegionColumns = [
  { accessorKey: 'regio', header: 'Region' },
  { accessorKey: 'region_desc', header: 'Region Name' },
  { accessorKey: 'netsales1', header: 'NET SALES(H = A-B-C-D)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT(N+U)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  // { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  // { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },

  // { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  // { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  // { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  // { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  // { accessorKey: 'pend_pick1', header: 'PENDING PICKLIST(L)' },
  // { accessorKey: 'total1', header: 'O(H+L)' },
  // { accessorKey: 'pend_ord1', header: 'PENDING ORDER(M)' },
  // { accessorKey: 'total_ord1', header: 'N(O+M)' },
  // { accessorKey: 'unconf_ord1', header: 'UNCONF ORDER VALUE(U)' },
  // { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  // { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  // { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  // { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
]
