export const Salescolumns = [
  { accessorKey: 'division', header: 'DIV' },
  { accessorKey: 'name', header: 'DIV NAME' },
  { accessorKey: 'sale', header: 'GROSS SALE(A)' },
  { accessorKey: 'saleable', header: 'SALEABLE RET. (B)' },
  { accessorKey: 'nonsaleable', header: 'NON-SALEABLE RET. (C)' },
  { accessorKey: 'diff', header: 'PRICE DIFF RET.(D)' },
  { accessorKey: 'netsales', header: 'NET SALES (E=A-B-C-D)' },
  { accessorKey: 'pend_pick', header: 'PENDING FOR INVOICE (F)' },
  { accessorKey: 'pend_ord', header: 'PENDING FOR PACKING (G)' },
  { accessorKey: 'pend_disp', header: 'PENDING FOR DISPATCHES H(F+G)' },
  { accessorKey: 'unconf_ostd_ord', header: 'UNCONF DUE TO OS (I)' },
  { accessorKey: 'unconf_stock', header: 'UNCONF DUE TO STOCK (J)' },
  { accessorKey: 'unconf_total', header: 'TOTAL UNCONF (K=I+J)' },
  { accessorKey: 'for_ord', header: 'SCORE CARD' },
  { accessorKey: 'net_amt', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACHIEVEMENT (%)' },
  { accessorKey: 'varv', header: 'VAR' },
  { accessorKey: 'percRet', header: '% RET' },
  { accessorKey: 'lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'lymtd1', header: 'LAST YEAR' },
  { accessorKey: 'growth_cy', header: 'LAST YEAR GROWTH' },
];

export const divHqPopupColumns = [
  { accessorKey: 'division1', header: 'Div' },
  { accessorKey: 'name1', header: 'Div Name' },
  { accessorKey: 'vkbur', header: 'HQ' },
  { accessorKey: 'bezei', header: 'HQ NAME' },
  { accessorKey: 'msr', header: 'MSR' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES (E=A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING FOR INVOICE (F)' },
  { accessorKey: 'pend_ord1', header: 'PENDING FOR PACKING (G)' },
  { accessorKey: 'pend_disp', header: 'PENDING FOR DISPATCHES H(F+G)' },
  { accessorKey: 'unconf_ostd_ord1', header: 'UNCONF DUE TO OS (I)' },
  { accessorKey: 'unconf_stock', header: 'UNCONF DUE TO STOCK (J)' },
  { accessorKey: 'unconf_total', header: 'TOTAL UNCONF (K=I+J)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'percRet', header: '% RET' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
  { accessorKey: 'ytoamt', header: 'OS' },
  { accessorKey: 'tcamt1', header: 'Collection' },
  { accessorKey: 'ttgt_coll', header: 'Collection Target' },
  { accessorKey: 'mcamt1', header: 'Collection LMTD' },
  { accessorKey: 'ycamt1', header: 'Collection LYTD' },
];

export const divBrandPopupColumns = [
  { accessorKey: 'division1', header: 'Div' },
  { accessorKey: 'name1', header: 'Div Name' },
  { accessorKey: 'brand_code', header: 'BRAND CODE' },
  { accessorKey: 'brand_name', header: 'BRAND NAME' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES (H=A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING FOR PACKING (L)' },
  { accessorKey: 'total1', header: 'O(H+L)' },
  { accessorKey: 'pend_ord1', header: 'PENDING ORDER (M)' },
  { accessorKey: 'total_ord1', header: 'N(O+M)' },
  { accessorKey: 'unconf_ord1', header: 'UNCONF ORDER VALUE (U)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
];

export const divHierarchyPopupColumns = [
  { accessorKey: 'div', header: 'Division' },
  { accessorKey: 'name', header: 'Dsm/Rm Name' },
  { accessorKey: 'scorecard', header: 'ScoreCard' },
  { accessorKey: 'net_amount', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'var', header: 'VAR' },
  { accessorKey: 'percRet', header: '% RET' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
];

export const divPlantPopupColumns = [
  { accessorKey: 'werks', header: 'Plant' },
  { accessorKey: 'plant', header: 'Plant Name' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES(E = A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING FOR INVOICE (F)' },
  { accessorKey: 'pend_ord1', header: 'PENDING FOR PACKING (G)' },
  { accessorKey: 'pend_disp', header: 'PENDING FOR DISPATCHES H(F+G)' },
  { accessorKey: 'unconf_ostd_ord1', header: 'UNCONF DUE TO OS (I)' },
  { accessorKey: 'unconf_stock', header: 'UNCONF DUE TO STOCK (J)' },
  { accessorKey: 'unconf_total', header: 'TOTAL UNCONF (K=I+J)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR' },
  { accessorKey: 'ytoamt', header: 'OS' },
  { accessorKey: 'tcamt1', header: 'Collection' },
  { accessorKey: 'ttgt_coll', header: 'Collection Target' },
  { accessorKey: 'mcamt1', header: 'Collection LMTD' },
  { accessorKey: 'ycamt1', header: 'Collection LYTD' },
];

export const divCustPopupColumns = [
  { accessorKey: 'kunnr', header: 'Customer' },
  { accessorKey: 'name1', header: 'Customer Name' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES(E = A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING FOR INVOICE (F)' },
  { accessorKey: 'pend_ord1', header: 'PENDING FOR PACKING (G)' },
  { accessorKey: 'pend_disp', header: 'PENDING FOR DISPATCHES H(F+G)' },
  { accessorKey: 'unconf_ostd_ord1', header: 'UNCONF DUE TO OS (I)' },
  { accessorKey: 'unconf_stock', header: 'UNCONF DUE TO STOCK (J)' },
  { accessorKey: 'unconf_total', header: 'TOTAL UNCONF (K=I+J)' },
  { accessorKey: 'status', header: 'Status' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT (E+H+K)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'percRet', header: '% RET' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'lmgrowth', header: 'LAST MONTH UPTO DATE GROWTH' },
  { accessorKey: 'growth', header: 'LAST YEAR UPTO DATE GROWTH' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
  { accessorKey: 'ytoamt', header: 'OS' },
  { accessorKey: 'tcamt1', header: 'Collection' },
  { accessorKey: 'ttgt_coll', header: 'Collection Target' },
  { accessorKey: 'mcamt1', header: 'Collection LMTD' },
  { accessorKey: 'ycamt1', header: 'Collection LYTD' },
];

export const RegionReportColumns = [
  { accessorKey: 'regio', header: 'Region' },
  { accessorKey: 'region_desc', header: 'Region Name' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES(H = A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING PICKLIST(L)' },
  { accessorKey: 'total1', header: 'O(H+L)' },
  { accessorKey: 'pend_ord1', header: 'PENDING ORDER(M)' },
  { accessorKey: 'total_ord1', header: 'N(O+M)' },
  { accessorKey: 'unconf_ord1', header: 'UNCONF ORDER VALUE(U)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT(N+U)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
]

export const ProductReportColumns = [
  { accessorKey: 'matnr', header: 'Material' },
  { accessorKey: 'maktx', header: 'Material Name' },
  { accessorKey: 'sale1', header: 'Gross Sale (A)' },
  { accessorKey: 'saleable1', header: 'Saleable Ret. (B)' },
  { accessorKey: 'nonsaleable1', header: 'Non-Saleable Ret. (C)' },
  { accessorKey: 'diff1', header: 'Price Diff Ret.(D)' },
  { accessorKey: 'netsales1', header: 'NET SALES(H = A-B-C-D)' },
  { accessorKey: 'pend_pick1', header: 'PENDING PICKLIST(L)' },
  { accessorKey: 'total1', header: 'O(H+L)' },
  { accessorKey: 'pend_ord1', header: 'PENDING ORDER(M)' },
  { accessorKey: 'total_ord1', header: 'N(O+M)' },
  { accessorKey: 'unconf_ord1', header: 'UNCONF ORDER VALUE(U)' },
  { accessorKey: 'net_amt1', header: 'NET AMOUNT(N+U)' },
  { accessorKey: 'target1', header: 'TARGET' },
  { accessorKey: 'achv', header: 'ACH (%)' },
  { accessorKey: 'v_lmtd', header: 'LAST MONTH UPTO DATE' },
  { accessorKey: 'v_lymtd', header: 'LAST YEAR UPTO DATE' },
  { accessorKey: 'v_lmtd1', header: 'LAST MONTH' },
  { accessorKey: 'v_lymtd1', header: 'LAST YEAR' },
]

export const regioPerformanceHead = [
  // { accessorKey: 'regio', header: 'Region' },
  { accessorKey: 'region_desc', header: 'Region Name' },
  { accessorKey: 'netsales1', header: 'Net Sales' },
  { accessorKey: 'net_amt1', header: 'Net Amount' },
  { accessorKey: 'target1', header: 'Target' },
  { accessorKey: 'achv', header: 'Ach(%)' },
];

export const brandPerformanceHead = [
  // { accessorKey: 'mvgr1', header: 'Brand Code' },
  { accessorKey: 'brand', header: 'Brand Name' },
  { accessorKey: 'gross_sale', header: 'Gross Sale' },
  { accessorKey: 'net_amt', header: 'Net Amount' },
  { accessorKey: 'target', header: 'Target' },
  { accessorKey: 'achv', header: 'Ach(%)' },
];

export const hqPerformanceHead = [
  { accessorKey: 'vkbur', header: 'Hq Code' },
  { accessorKey: 'bezei', header: 'Hq Name' },
  { accessorKey: 'msr', header: 'Msr' },
  { accessorKey: 'for_ord', header: 'ScoreCard' },
  { accessorKey: 'gross_sale', header: 'Gross Sale' },
  { accessorKey: 'net_amt1', header: 'Net Amount' },
  { accessorKey: 'target1', header: 'Target' },
  { accessorKey: 'achv', header: 'Ach(%)' },
];

export const hierarchyPerformanceHead = [
  { accessorKey: 'div', header: 'Division' },
  { accessorKey: 'name', header: 'Name' },
  { accessorKey: 'scorecard', header: 'ScoreCard' },
  { accessorKey: 'net_amount', header: 'Net Amount' },
  { accessorKey: 'target', header: 'Target' },
  { accessorKey: 'achv', header: 'Ach(%)' },
];

export const QuaterWiseProductSaleHeaderColumn = [
{ label: 'BRAND CODE', key: 'Products' },
{ label: 'BRAND', key: 'Name' },
{ label: 'VQ', key: 'VQ' },
{ label: 'SALE', key: 'TYS_QTR1' },
{ label: 'TARGET', key: 'TGT_QTR1' },
{ label: 'ACH', key: 'ACH_QTR1' },
{ label: 'VAR', key: 'CVR_QTR1' },
{ label: 'LYS', key: 'LYS_QTR1' },
{ label: 'GROWTH', key: 'GTH_QTR1' },
{ label: 'SALE', key: 'TYS_QTR2' },
{ label: 'TARGET', key: 'TGT_QTR2' },
{ label: 'ACH', key: 'ACH_QTR2' },
{ label: 'VAR', key: 'CVR_QTR2' },
{ label: 'LYS', key: 'LYS_QTR2' },
{ label: 'GROWTH', key: 'GTH_QTR2' },
{ label: 'SALE', key: 'TYS_QTR3' },
{ label: 'TARGET', key: 'TGT_QTR3' },
{ label: 'ACH', key: 'ACH_QTR3' },
{ label: 'VAR', key: 'CVR_QTR3' },
{ label: 'LYS', key: 'LYS_QTR3' },
{ label: 'GROWTH', key: 'GTH_QTR3' },
{ label: 'SALE', key: 'TYS_QTR4' },
{ label: 'TARGET', key: 'TGT_QTR4' },
{ label: 'ACH', key: 'ACH_QTR4' },
{ label: 'VAR', key: 'CVR_QTR4' },
{ label: 'LYS', key: 'LYS_QTR4' },
{ label: 'GROWTH', key: 'GTH_QTR4' },
{ label: 'SALE', key: 'TYS_TOTAL' },
{ label: 'TARGET', key: 'TGT_TOTAL' },
{ label: 'ACH', key: 'ACH_TOTAL' },
{ label: 'VAR', key: 'CVR_TOTAL' },
{ label: 'LYS', key: 'LYS_TOTAL' },
{ label: 'GROWTH', key: 'GTH_TOTAL' },
];


export const QuaterWiseProductSaleHeaderGroupColumn = [
{ label: 'DESCRIPTION', span: 3 },
{ label: 'QTR1', span: 6 },
{ label: 'QTR2', span: 6 },
{ label: 'QTR3', span: 6 },
{ label: 'QTR4', span: 6 },
{ label: 'ANNUAL TOTAL', span: 6 },
];

export const NetworkWiseProductSaleHeaderColumn =[
{ label: 'Products', key: 'Products' },
{ label: 'Name', key: 'Name' },
{ label: 'TAG', key: 'TAG' },
{ label: 'SALE', key: 'TYS' },
{ label: 'TGT', key: 'TGT' },
{ label: 'ACH', key: 'ACH' },
{ label: 'VAR', key: 'VAR' },
{ label: 'LYS', key: 'LYS' },
{ label: 'GROWTH', key: 'GROW' },
{ label: 'CSALE', key: 'CTYS' },
{ label: 'CTGT', key: 'CTGT' },
{ label: 'CACH', key: 'CACH' },
{ label: 'CVAR', key: 'CVAR' },
{ label: 'CLYS', key: 'CLYS' },
{ label: 'CGROW', key: 'CGROW' },
{ label: 'CONT', key: 'CONT' },
{ label: 'PROD', key: 'PROD' },
];

export const NetworkWiseProductSaleHeaderGroupColumn =[
{ label: 'DESCRIPTION', span: 3 },
{ label: 'financYear', span: 6 },
{ label: 'financYearStr', span: 8 },
];

export const NetworkWiseProductYearlySaleHeaderColumn =[
{ label: 'ProductCode', key: 'ProductCode' },
{ label: 'ProductDesc', key: 'ProductDesc' },
{ label: 'VQ', key: 'VQ' },
{ label: 'AprTYS', key: 'AprTYS' },
{ label: 'AprTGT', key: 'AprTGT' },
{ label: 'AprACH', key: 'AprACH' },
{ label: 'AprVAR', key: 'AprVAR' },
{ label: 'AprLYS', key: 'AprLYS' },
{ label: 'AprGTH', key: 'AprGTH' },
{ label: 'MayTYS', key: 'MayTYS' },
{ label: 'MayTGT', key: 'MayTGT' },
{ label: 'MayACH', key: 'MayACH' },
{ label: 'MayVAR', key: 'MayVAR' },
{ label: 'MayLYS', key: 'MayLYS' },
{ label: 'MayGTH', key: 'MayGTH' },
{ label: 'JunTYS', key: 'JunTYS' },
{ label: 'JunTGT', key: 'JunTGT' },
{ label: 'JunACH', key: 'JunACH' },
{ label: 'JunVAR', key: 'JunVAR' },
{ label: 'JunLYS', key: 'JunLYS' },
{ label: 'JunGTH', key: 'JunGTH' },
{ label: 'Q1TYS', key: 'Q1TYS' },
{ label: 'Q1TGT', key: 'Q1TGT' },
{ label: 'Q1ACH', key: 'Q1ACH' },
{ label: 'Q1VAR', key: 'Q1VAR' },
{ label: 'Q1LYS', key: 'Q1LYS' },
{ label: 'Q1GTH', key: 'Q1GTH' },
{ label: 'JulTYS', key: 'JulTYS' },
{ label: 'JulTGT', key: 'JulTGT' },
{ label: 'JulACH', key: 'JulACH' },
{ label: 'JulVAR', key: 'JulVAR' },
{ label: 'JulLYS', key: 'JulLYS' },
{ label: 'JulGTH', key: 'JulGTH' },
{ label: 'AugTYS', key: 'AugTYS' },
{ label: 'AugTGT', key: 'AugTGT' },
{ label: 'AugACH', key: 'AugACH' },
{ label: 'AugVAR', key: 'AugVAR' },
{ label: 'AugLYS', key: 'AugLYS' },
{ label: 'AugGTH', key: 'AugGTH' },
{ label: 'SepTYS', key: 'SepTYS' },
{ label: 'SepTGT', key: 'SepTGT' },
{ label: 'SepACH', key: 'SepACH' },
{ label: 'SepVAR', key: 'SepVAR' },
{ label: 'SepLYS', key: 'SepLYS' },
{ label: 'SepGTH', key: 'SepGTH' },
{ label: 'Q2TYS', key: 'Q2TYS' },
{ label: 'Q2TGT', key: 'Q2TGT' },
{ label: 'Q2ACH', key: 'Q2ACH' },
{ label: 'Q2VAR', key: 'Q2VAR' },
{ label: 'Q2LYS', key: 'Q2LYS' },
{ label: 'Q2GTH', key: 'Q2GTH' },
{ label: 'H1TYS', key: 'H1TYS' },
{ label: 'H1TGT', key: 'H1TGT' },
{ label: 'H1ACH', key: 'H1ACH' },
{ label: 'H1VAR', key: 'H1VAR' },
{ label: 'H1LYS', key: 'H1LYS' },
{ label: 'H1GTH', key: 'H1GTH' },
{ label: 'OctTYS', key: 'OctTYS' },
{ label: 'OctTGT', key: 'OctTGT' },
{ label: 'OctACH', key: 'OctACH' },
{ label: 'OctVAR', key: 'OctVAR' },
{ label: 'OctLYS', key: 'OctLYS' },
{ label: 'OctGTH', key: 'OctGTH' },
{ label: 'NovTYS', key: 'NovTYS' },
{ label: 'NovTGT', key: 'NovTGT' },
{ label: 'NovACH', key: 'NovACH' },
{ label: 'NovVAR', key: 'NovVAR' },
{ label: 'NovLYS', key: 'NovLYS' },
{ label: 'NovGTH', key: 'NovGTH' },
{ label: 'DecTYS', key: 'DecTYS' },
{ label: 'DecTGT', key: 'DecTGT' },
{ label: 'DecACH', key: 'DecACH' },
{ label: 'DecVAR', key: 'DecVAR' },
{ label: 'DecLYS', key: 'DecLYS' },
{ label: 'DecGTH', key: 'DecGTH' },
{ label: 'Q3TYS', key: 'Q3TYS' },
{ label: 'Q3TGT', key: 'Q3TGT' },
{ label: 'Q3ACH', key: 'Q3ACH' },
{ label: 'Q3VAR', key: 'Q3VAR' },
{ label: 'Q3LYS', key: 'Q3LYS' },
{ label: 'Q3GTH', key: 'Q3GTH' },
{ label: 'JanTYS', key: 'JanTYS' },
{ label: 'JanTGT', key: 'JanTGT' },
{ label: 'JanACH', key: 'JanACH' },
{ label: 'JanVAR', key: 'JanVAR' },
{ label: 'JanLYS', key: 'JanLYS' },
{ label: 'JanGTH', key: 'JanGTH' },
{ label: 'FebTYS', key: 'FebTYS' },
{ label: 'FebTGT', key: 'FebTGT' },
{ label: 'FebACH', key: 'FebACH' },
{ label: 'FebVAR', key: 'FebVAR' },
{ label: 'FebLYS', key: 'FebLYS' },
{ label: 'FebGTH', key: 'FebGTH' },
{ label: 'MarTYS', key: 'MarTYS' },
{ label: 'MarTGT', key: 'MarTGT' },
{ label: 'MarACH', key: 'MarACH' },
{ label: 'MarVAR', key: 'MarVAR' },
{ label: 'MarLYS', key: 'MarLYS' },
{ label: 'MarGTH', key: 'MarGTH' },
{ label: 'Q4TYS', key: 'Q4TYS' },
{ label: 'Q4TGT', key: 'Q4TGT' },
{ label: 'Q4ACH', key: 'Q4ACH' },
{ label: 'Q4VAR', key: 'Q4VAR' },
{ label: 'Q4LYS', key: 'Q4LYS' },
{ label: 'Q4GTH', key: 'Q4GTH' },
{ label: 'H2TYS', key: 'H2TYS' },
{ label: 'H2TGT', key: 'H2TGT' },
{ label: 'H2ACH', key: 'H2ACH' },
{ label: 'H2VAR', key: 'H2VAR' },
{ label: 'H2LYS', key: 'H2LYS' },
{ label: 'H2GTH', key: 'H2GTH' },
{ label: 'YrTYS', key: 'YrTYS' },
{ label: 'YrTGT', key: 'YrTGT' },
{ label: 'YrACH', key: 'YrACH' },
{ label: 'YrVAR', key: 'YrVAR' },
{ label: 'YrLYS', key: 'YrLYS' },
{ label: 'YrGTH', key: 'YrGTH' }
];


export const hierarchyWiseReportHeader = [
{ label: 'Name', key: '_displayName' },
{ label: 'Designation', key: 'desg' },
{ label: 'MSR', key: 'msr' },
{ label: 'TYS', key: 'tys' },
{ label: 'TGT', key: 'tgt' },
{ label: 'LYS', key: 'lys' },
{ label: 'Var', key: 'var' },
{ label: 'Ach(%)', key: 'ach' },
{ label: 'Growth', key: 'gth' },
{ label: 'Cum TYS', key: 'ctys' },
{ label: 'Cum TGT', key: 'ctgt' },
{ label: 'Cum LYS', key: 'clys' },
{ label: 'Cum Var', key: 'cvar' },
{ label: 'Cum Ach(%)', key: 'cah' },
{ label: 'Cum Growth', key: 'cgth' },
];